### ISSUE TITLE
Beamsize not being correctly put into ispyb

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1412] opened 2024-05-24 12:50 UTC
When testing the new release, we found that the beamsize wasn't being put into ispyb: https://ispyb.diamond.ac.uk/dc/visit/cm37235-2/id/14117910

## Acceptance Criteria
Issue identified, fixed, and tested

**Comment by rtuck99** [comment] 2024-05-29 09:58
Seems like the code was there, `read_hardware_for_ispyb_pre_collection` gets called, however none of the hardware read info is saved to the DB.

In the ispyb_callback log file for the collection we can see:
```
[2024-05-21 14:23:02,813] Hyperion ISPyB and Zocalo callbacks plan_reactive_callback ERROR: DatabaseError(-1): Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 564, in _process_params
    res = [to_mysql(value) for value in res]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 564, in <listcomp>
    res = [to_mysql(value) for value in res]
           ^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/conversion.py", line 237, in to_mysql
    raise TypeError(
TypeError: Python 'ca_float' cannot be converted to a MySQL type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/ispyb/connector/mysqlsp/main.py", line 97, in call_sp_write
    result_args = cursor.callproc(procname=procname, args=args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 950, in callproc
    self.execute(f"SET {placeholders}", argvalues)
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 730, in execute
    psub = _ParamSubstitutor(self._process_params(params))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 571, in _process_params
    raise ProgrammingError(
mysql.connector.errors.ProgrammingError: Failed processing format-parameters; Python 'ca_float' cannot be converted to a MySQL type
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 564, in _process_params
    res = [to_mysql(value) for value in res]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/cursor.py", line 564, in <listcomp>
    res = [to_mysql(value) for value in res]
           ^^^^^^^^^^^^^^^
  File "/dls_sw/i03/software/bluesky/hyperion_v9.3.1/hyperion/.venv/lib/python3.11/site-packages/mysql/connector/conversion.py", line 237, in to_mysql
    raise TypeError(
TypeError: Python 'ca_float' cannot be converted to a MySQL type

```
etc

**Comment by rtuck99** [comment] 2024-05-29 10:00
This is a duplicate of #1417

**Closed by rtuck99** 2024-05-29 10:00 UTC
Labels: duplicate
