### ISSUE TITLE
Beam centre getting increasing number of calls

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1075] opened 2024-01-16 12:15 UTC
When running Hyperion we're getting increasing logs like https://graylog2.diamond.ac.uk/messages/logs_8609/4d842b50-b468-11ee-a034-1866dafadc6c

As in the first run will give one message and the second two etc.

This is likely due to a callback being added somewhere everytime Hyperion is run.

## Acceptance Criteria
* The callback is only ever added once
* There is a test for this

**Comment by olliesilvester** [comment] 2024-01-16 14:23
It looks like this is caused by a callback being subscribed on `wait_for_connection` rather than in init, in `OAV`

**Comment by olliesilvester** [comment] 2024-01-17 10:22
The fix for this is on I03 now. I'll keep an eye on the logs to make sure it's actually fixed

**Closed** 2024-01-17 14:51 UTC
Labels: needed_for_release
